/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/room.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Room(props) {
  const { nodes, materials } = useGLTF('/room.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.073, -0.96, -5.216]} rotation={[-1.467, 0, 0.868]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Kitchen_Palette_0.geometry} material={materials.Palette} position={[82.703, 112.092, -29.398]} rotation={[0, -Math.PI / 2, 0]} scale={[0.899, 0.6, 0.6]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/room.glb')
